name: First Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
       
      - name: Run a sample checkout action
        run: echo "Checking out your repo ran successfully"

      - name: Simulating Error
        run: echo "Error Taking Place"; exit 1
    
