name: First Workflow

on: push

jobs:
  build:
    run-ons: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     
     - name: Run a sample checkout action
       run: echo "Checking out your repo ran successfully"
    
